### ISSUE TITLE
Updating record failed with the result 'error'

### ISSUE THREAD

**Issue by IDmedia** [thatjpk/cloudflare-ddns#12]
The script works nicely with sub-domains such as foo.bar.com, but when trying to update bar.com I only receive "Updating record failed with the result 'error'" if the IP has changed.

My config is bar_naked.yaml with cf_domain set to 'bar.com' and cf_subdomain set to ''.
Anything else I should be aware of?

**Comment by thatjpk** [comment]
Hm, this used to work but trying it myself just now, it doesn't.  However, apparently if you set both `cf_domain` and `cf_subdomain` to 'bar.com', it'll update the A record you're after.  Try that.

**Comment by thatjpk** [comment]
Closing this.  Feel free to reopen if you have any further questions.
