### ISSUE TITLE
Need to support Version 4 API

### ISSUE THREAD

**Issue by JerryDurand** [thatjpk/cloudflare-ddns#14]
Cloudflare is turning off the version 1 API we all know and love on November 9th.  They want all of us to use version 4.

**Comment by thatjpk** [comment]
Thanks for the heads-up

**Comment by JerryDurand** [comment]
The best I can tell, you have to GET the current settings as a JSON block and then PUT most of them back.  I've been doing some testing to see how few items have to be written back and it looks like the minimum is
`--data '{"id":"...","type":"A","name":"...","content":"'$ip'","proxiable":...,"proxied":...,"ttl":...,"locked":false}'`
where ... is replaced by valid data.  This may or may not hold in general, I've only tested it in one case so far.

So, GET whole block, extract the bits we have to send back, and then do the PUT.

I REALLY don't like systems where I have to write data that I'm not changing.  I only want to write the individual items I'm changing and have the rest stay as they are.

**Comment by thatjpk** [comment]
Good to know.  Strictly speaking, the semantics of the PUT method in REST-ish APIs is to send everything.  Partial updates should be done with PATCH, but API implementers rarely do this.

**Comment by thatjpk** [comment]
Note to self: [documentation](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record).

**Comment by thatjpk** [comment]
Got some stuff going on this month, so targeting first weekend in November (5-6th) to look at this.

**Comment by thatjpk** [comment]
@JerryDurand Again, thanks for the heads up on this.  Should be good to go for the new API.  :)

**Comment by JerryDurand** [comment]
Thanks, will test shortly.  Currently running on a hard-coded script I tossed together.
